In [16]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.50,0.7,1,0,0.5])

Mean Absolute Error

In [17]:
# mean absolute error

def mae(y_true, y_predicted):
  total_error = 0
  for yt, yp in zip(y_true, y_predicted):
    total_error += abs(yt-yp)

  print("Total error: ", total_error)
  mae = total_error / len(y_predicted)
  print("MAE: ", mae)
  return mae

In [18]:
mae(y_true, y_predicted)

Total error:  2.3
MAE:  0.45999999999999996


0.45999999999999996

In [19]:
np.mean(np.abs(y_predicted - y_true))

0.45999999999999996

Mean Squared Error

In [20]:
def mse(y_true, y_predicted):
  total_error = 0
  for yt, yp in zip(y_true, y_predicted):
    total_error += abs(yt-yp) * abs(yt-yp)

  print("Total error: ", total_error)
  mse = total_error / len(y_predicted)
  print("MSE: ", mse)
  return mse

In [21]:
mse(y_true, y_predicted)

Total error:  1.59
MSE:  0.318


0.318

In [22]:
np.mean(np.power(np.abs(y_predicted - y_true), 2))

0.318

Log loss or Binary Cross Entropy

In [23]:
# log of zero is not defined

np.log([0])

<ipython-input-23-93d288a9d8cd>:3: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [24]:

np.log([0.0000000000000000000001])

array([-50.65687205])

In [25]:
epsilon  = 1e-15
epsilon

1e-15

In [26]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [27]:
y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [33]:
y_predicted_new = np.array(y_predicted_new)
y_predicted_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [34]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [35]:
np.log(y_predicted)

<ipython-input-35-d8d657355a01>:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [36]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

15.888045036990766

In [41]:
def log_loss_function(y_true, y_predicted):
  epsilon = 1e-15
  y_predicted_new = [max(i, epsilon) for i in y_predicted]
  y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new))

In [42]:
log_loss_function(y_true, y_predicted)

15.888045036990766